2025-07-06 04:30:11,525 - trm_api.db.session - DEBUG - Neomodel configured to connect to Neo4j on: {host}
2025-07-06 04:30:11,525 - trm_api.db.session - DEBUG - Neomodel configured to connect to Neo4j on: {host}
2025-07-06 04:30:11,526 - uvicorn.error - INFO - Application startup complete.
2025-07-06 04:30:11,528 - uvicorn.error - ERROR - Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\runners.py", line 123, in run
    raise KeyboardInterrupt()
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "E:\tech\trm-os-branches\trm_api\main.py", line 31, in lifespan
    yield
  File "E:\tech\trm-os-branches\venv-trm\Lib\site-packages\starlette\routing.py", line 743, in lifespan
    await receive()
  File "E:\tech\trm-os-branches\venv-trm\Lib\site-packages\uvicorn\lifespan\on.py", line 137, in receive
    return await self.receive_queue.get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\queues.py", line 158, in get
    await getter
asyncio.exceptions.CancelledError

2025-07-06 04:30:12,558 - trm_api.db.session - DEBUG - Neomodel configured to connect to Neo4j on: {host}
2025-07-06 04:30:12,558 - trm_api.db.session - DEBUG - Neomodel configured to connect to Neo4j on: {host}
2025-07-06 04:30:12,558 - uvicorn.error - INFO - Application startup complete.
2025-07-06 05:34:59,858 - uvicorn.error - INFO - Shutting down
2025-07-06 05:34:59,965 - uvicorn.error - INFO - Waiting for application shutdown.
2025-07-06 05:34:59,975 - trm_api.db.session - DEBUG - Database connection managed by neomodel's thread-local driver. No explicit close action needed.
2025-07-06 05:34:59,975 - trm_api.db.session - DEBUG - Database connection managed by neomodel's thread-local driver. No explicit close action needed.
2025-07-06 05:34:59,976 - uvicorn.error - INFO - Application shutdown complete.
2025-07-06 05:34:59,976 - uvicorn.error - INFO - Finished server process [27924]
2025-07-06 05:35:00,913 - trm_api.db.session - DEBUG - Neomodel configured to connect to Neo4j on: {host}
2025-07-06 05:35:00,913 - trm_api.db.session - DEBUG - Neomodel configured to connect to Neo4j on: {host}
2025-07-06 05:35:00,914 - uvicorn.error - INFO - Application startup complete.
2025-07-06 05:35:00,916 - uvicorn.error - ERROR - Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\runners.py", line 123, in run
    raise KeyboardInterrupt()
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "E:\tech\trm-os-branches\trm_api\main.py", line 31, in lifespan
    yield
  File "E:\tech\trm-os-branches\venv-trm\Lib\site-packages\starlette\routing.py", line 743, in lifespan
    await receive()
  File "E:\tech\trm-os-branches\venv-trm\Lib\site-packages\uvicorn\lifespan\on.py", line 137, in receive
    return await self.receive_queue.get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\queues.py", line 158, in get
    await getter
asyncio.exceptions.CancelledError

2025-07-06 05:35:01,768 - trm_api.db.session - DEBUG - Neomodel configured to connect to Neo4j on: {host}
2025-07-06 05:35:01,768 - trm_api.db.session - DEBUG - Neomodel configured to connect to Neo4j on: {host}
2025-07-06 05:35:01,768 - uvicorn.error - INFO - Application startup complete.
